### ISSUE TITLE
NAPALM

### ISSUE THREAD

**Issue by eegilbert** [jonasstenling/iosxe-ansible#1]
Hi,

I was curious if you'd looked at the [napalm](https://github.com/napalm-automation/) project at all? I dont' see an IOS-XE module yet.

Cheers,

Erric

**Comment by jonasstenling** [comment]
Yes, I did look at NAPALM, but at the time it was still in its infancy. I
guess it would be a great idea to also write support for IOS XE in NAPALM!
:-)
